import { StyleSheet } from 'react-native';

const journalstyles = StyleSheet.create({
    container: {
        flexGrow: 1,
        padding: 20,
        justifyContent: 'flex-start',

    },
    title: {
        fontSize: 32,
        fontWeight: 'bold',
        marginBottom: 20,
        color: '#333',
        textAlign: 'center',
    },
    dateContainer: {
        marginBottom: 20,
        alignItems: 'center',
    },
    label: {
        fontSize: 16,
        fontWeight: '500',
        color: 'black',
        marginBottom: 8,
    },
    titleContainer: {
        marginBottom: 20,
        borderColor: '#007BFF',
        borderWidth: 2,
        borderRadius: 8,
        padding: 10,
        backgroundColor: 'rgba(255, 255, 255, 0.7)', 
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    journalContainer: {
        flex: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.7)', 
        borderColor: '#007BFF',
        borderWidth: 2,
        borderRadius: 8,
        padding: 8,
        marginBottom: 20,
    },
    textInput: {
        fontSize: 16,
        textAlignVertical: 'top',
        color: '#333',
    },
    navigationButton: {
        marginTop: 20,
        backgroundColor: '#007BFF',
        borderRadius: 8,
        padding: 10,
    },
    buttonText: {
        color: '#fff',
        textAlign: 'center',
        fontSize: 16,
        fontWeight: '500',
    },
    cameraButton: {
        alignSelf: 'center',
        backgroundColor: '#007BFF',
        borderRadius: 50,
        padding: 10,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    imageStyle: {
        width: '30%', 
        height: 80,    
        resizeMode: 'contain',  
        marginTop: 10,
    },
    removeIcon: {
        position: 'absolute',
        top: 5,
        left: 90,
        backgroundColor: 'white',
        borderRadius: 12,
    },
    audioContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginVertical: 15,
        paddingVertical: 15,
        width: 200,
        paddingHorizontal: 20,
        backgroundColor: '#f1f1f1', 
        borderRadius: 20, 
        shadowColor: '#000', 
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 5, 
    },
    playPauseButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#007BFF',
        justifyContent: 'center',
        alignItems: 'center',
    },
    progressBarContainer: {
        flex: 1,
        height: 8,
        backgroundColor: '#ddd',
        borderRadius: 4,
        marginHorizontal: 15,
    },
    progressBar: {
        height: 8,
        backgroundColor: '#007BFF',
        borderRadius: 4,
    },
    progressTime: {
        fontSize: 12,
        color: '#555',
        width: 40,
        textAlign: 'center',
    },
    audioIcon: {
        position: 'absolute',
        top: 0,
        right: 0,
        backgroundColor: 'white',
        borderRadius: 12,
    },
    galleryButton: {
        alignSelf: 'center',
        backgroundColor: '#007BFF',
        borderRadius: 50,
        padding: 10,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    galleryIcon: {
        width: 30,
        height: 30,
    },
    imageStyle: {
        width: '30%',
        height: 80,
        resizeMode: 'contain',
        marginTop: 10,
    }

});

export default journalstyles;
